### PR TITLE
Kp/tailwind config

### PR DESCRIPTION
**Pull request by KP824**
## Overview
**Tailwind configuration**
KP/tailwind_config

- [ ] Bug
- [x] Feature
- [ ] Tech Debt

**Description**
Installation to enable tailwind styling for front end.

**Ticket Item**
https://trello.com/c/l6KmOx5R

**Steps to Reproduce Bug / Validate Feature / Confirm Tech Debt Fix**
1. Change directory to web-app
2. npm install to install tailwind
3. In the terminal, run the following command to build the tailwind the final CSS file:
```
npx tailwindcss -i ./TS_src/client/stylesheets/index.css -o ./dist/output.css --watch
```

**Expected behavior**
Now able to style components using tailwind.

### CODE REVIEW

**Comment by wendyys96** [comment]
Hi Kevin. I think the pull request has been made to the main branch. Is it meant to be for dev?

**Comment by KP824** [comment]
> Hi Kevin. I think the pull request has been made to the main branch. Is it meant to be for dev?

Thank you for catching this Yeong. I have updated the pull request to dev branch.

**Review by larkinaj — APPROVED** [review]
Approved -AL

**Review by wendyys96 — APPROVED** [review]
Approved

**Pull request merged**
